presets:
  tv:


    series:
      settings:
        tv:
          quality: <=720p
      tv:
        - STARTINDICATORDONOTREMOVE
        - Better Call Saul
        - 12 Monkeys
        - The Flash
        - The Librarians
        - Flash
        - Twelve Monkeys
        - Sons of Anarchy
        - Arrow
        - South Park
        - Big Bang Theory
        - The Walking Dead
        - Hostages
        - New Girl
        - Supernatural
        - How I Met Your Mother
        - Suits
        - The Mentalist
        - Person of Interest
        - Justified
        - Nikita
        - Game of Thrones
        - Greys Anatomy
        - White Collar
        - Elementary
        - Marvels Agents of S H I E L D    
        - Vikings
        - Castle
        - Homeland
        - Hannibal
        - True Blood
        - Mythbusters
        - Banshee  
        - Brooklyn Nine Nine
        - Top Gear
        - Cosmos A Space Time Odyssey
        - 24
        - Fargo
        - Legends 2014
        - Hell on Wheels
        - Gotham
        - Forever US
        - Transporter The Series
        - True Detective
        - Mr Robot
        - Last Week Tonight With John Oliver
        - Welcome to Sweden
    deluge: yes

tasks:
#  eztv-feed:
#    priority: 1
#    rss: http://ezrss.it/feed
#    preset: tv

#  bt-chat.com-tv:
#    priority: 2
#    rss: http://rss.bt-chat.com/?group=3
#    preset: tv

#  thepiratebay.org-tv:
#    priority: 3
#    rss: http://rss.thepiratebay.org/208
#    preset: tv
#    verify_ssl_certificates: yes

#  kat.ph-tv:
#    priority: 4
#    rss: http://kat.ph/tv/?rss=1
#    preset: tv

#  extratorrent.com-tv:
#    priority: 5
#    rss: http://extratorrent.com/rss.xml?cid=8
#    preset: tv

  torrentz.eu-tv:
    priority: 3
    rss: http://torrentz.eu/feed
    preset: tv

  showrss:
    priority: 4
#    rss: http://showrss.info/rss.php?user_id=263333&hd=2&proper=1
    rss: http://showrss.info/feeds/all.rss
    preset: tv

#  extratorrent:
#    rss: http://extratorrent.com/rss.xml?cid=8
#    preset: tv

#  showrss.karmorra.info-tv:
#    priority: 7
#    rss: http://showrss.karmorra.info/feeds/all.rss
#    preset: tv






